trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: TMPV-Openai-Backend-Appservice-vars

stages:
  - stage: Build
    displayName: 'Build Stage'
    
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:
        
        - task: UsePythonVersion@0
          displayName: 'python version'
          inputs:
            versionSpec: '3.10'
            addToPath: true
            architecture: 'x64'
        
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              python -m venv antenv
              . antenv/bin/activate
              pip install -r requirements.txt

        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(buildDirectory)'
            includeRootFolder: false
            archiveType: zip
            archiveFile: '$(artifactPath)'
            replaceExistingArchive: true 

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(artifactPath)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

  - stage: Release
    displayName: 'Release Stage'
    dependsOn: Build
    jobs:
      - deployment: DeployToAppService
        displayName: 'Deploy to Azure App Service'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    appType: 'webAppLinux'
                    appName: '$(appServiceName)'
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    startUpCommand: 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app'
                    appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT true'

  - stage: ProdRelease
    displayName: 'Prod Release Stage'
    dependsOn: Build
    jobs:
      - deployment: DeployToAppService
        displayName: 'Deploy to prod Azure App Service'
        environment: 'prod'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    appType: 'webAppLinux'
                    appName: '$(appServiceNameProd)'
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    startUpCommand: 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app'
                    appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT true'